version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/client"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "pip"
    directory: "/logger"
    schedule:
      interval: weekly
    target-branch: dev

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
